spring:
  profiles:
      active: dev
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
eureka:
  client:
    serviceUrl:
      defaultZone: http://117.78.33.168:30279/eureka/
  instance:
    preferIpAddress: true