server:
  port: 9411
  tomcat:
    uri-encoding: UTF-8
eureka:
  client:
    serviceUrl:
      defaultZone: http://114.115.172.242:8761//eureka/
  instance:
    preferIpAddress: true
#####设置日志######
logging:
   file: ..//logs//zipkin.log
   level:
     root: info