server:
  port: 30000
info:
    version: @project.version@
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://114.115.172.242:8761//eureka/
#####设置日志######
logging:
   file: ..//logs//monitor.log
   level:
     root: info